version: "3"
services:
  broomsticks:
    image: theoafactor/broomsticks:1.2.0
    restart: always
    ports:
      - 4443:3000
  mongodb:
    image: mongo
    restart: always
    volumes: 
      - mystorage:/data/db
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  
  mongoexpresso:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mystorage:
    driver: local
  